export type QuestionType = 'text' | 'textarea' | 'select' | 'multiselect' | 'file';

export interface OnboardingQuestion {
    id: string;
    label: string;
    type: QuestionType;
    required: boolean;
    options?: string[];
    groupedOptions?: Record<string, string[]>;
    placeholder?: string;
}

// Comprehensive subject options grouped by category
export const SUBJECT_OPTIONS: Record<string, string[]> = {
    'Cambridge Subjects': [
        'Anglo-Saxon, Norse, and Celtic',
        'Archaeology',
        'Architecture',
        'Asian and Middle Eastern Studies',
        'Chemical Engineering and Biotechnology',
        'Classics',
        'Computer Science',
        'Design',
        'Economics',
        'Education',
        'Engineering',
        'English',
        'Geography',
        'History',
        'History and Modern Languages',
        'History and Politics',
        'History of Art',
        'Human, Social, and Political Sciences',
        'Land Economy',
        'Law',
        'Linguistics',
        'Mathematics',
        'Medicine',
        'Modern and Medieval Languages',
        'Music',
        'Natural Sciences',
        'Philosophy',
        'Psychological and Behavioural Sciences',
        'Theology, Religion, and Philosophy of Religion',
        'Veterinary Medicine'
    ],
    'Oxford Subjects': [
        'Archaeology and Anthropology',
        'Asian and Middle Eastern Studies',
        'Biochemistry (Molecular and Cellular)',
        'Biology',
        'Biomedical Sciences',
        'Chemistry',
        'Classical Archaeology and Ancient History',
        'Classics',
        'Classics and Asian and Middle Eastern Studies',
        'Classics and English',
        'Classics and Modern Languages',
        'Computer Science',
        'Computer Science and Philosophy',
        'Earth Sciences (Geology)',
        'Economics and Management',
        'Engineering Science',
        'English Language and Literature',
        'English and Modern Languages',
        'European and Middle Eastern Languages',
        'Fine Art',
        'Geography',
        'History',
        'History (Ancient and Modern)',
        'History and Economics',
        'History and English',
        'History and Modern Languages',
        'History and Politics',
        'History of Art',
        'Human Sciences',
        'Law (Jurisprudence)',
        'Materials Science',
        'Mathematics',
        'Mathematics and Computer Science',
        'Mathematics and Philosophy',
        'Mathematics and Statistics',
        'Medicine',
        'Modern Languages',
        'Modern Languages and Linguistics',
        'Music',
        'Philosophy and Modern Languages',
        'Philosophy, Politics and Economics (PPE)',
        'Philosophy and Theology',
        'Physics',
        'Physics and Philosophy',
        'Psychology (Experimental)',
        'Psychology, Philosophy and Linguistics',
        'Religion and Asian and Middle Eastern Studies',
        'Theology and Religion'
    ],
    'Oxbridge Entrance Exams': [
        'TMUA (Test of Mathematics for University Admission)',
        'UCAT (University Clinical Aptitude Test)',
        'BMAT (BioMedical Admissions Test)',
        'ESAT (Engineering and Science Admissions Test)',
        'PAT (Physics Aptitude Test)',
        'MAT (Mathematics Admissions Test)',
        'HAT (History Aptitude Test)',
        'ELAT (English Literature Admissions Test)',
        'CAT (Cambridge Law Test)',
        'LNAT (Law National Aptitude Test)',
        'TSA (Thinking Skills Assessment)',
        'MLAT (Modern Languages Admissions Test)',
        'OLAT (Oriental Languages Aptitude Test)',
        'GAT (Geography Admissions Test)',
        'STEP (Sixth Term Examination Paper)'
    ],
    'GCSE Subjects': [
        'English Language',
        'English Literature',
        'Mathematics',
        'Biology',
        'Chemistry',
        'Physics',
        'Combined Science',
        'History',
        'Geography',
        'French',
        'Spanish',
        'German',
        'Art and Design',
        'Music',
        'Drama',
        'Physical Education',
        'Religious Studies',
        'Computer Science',
        'Business Studies',
        'Economics',
        'Sociology',
        'Psychology',
        'Latin',
        'Ancient Greek'
    ],
    'A-Level Subjects': [
        'Mathematics',
        'Further Mathematics',
        'Physics',
        'Chemistry',
        'Biology',
        'English Literature',
        'History',
        'Geography',
        'Economics',
        'Psychology',
        'Computer Science',
        'French',
        'Spanish',
        'German',
        'Art and Design',
        'Music',
        'Drama and Theatre',
        'Philosophy',
        'Politics',
        'Sociology',
        'Law',
        'Business Studies',
        'Classical Civilisation',
        'Latin',
        'Ancient Greek',
        'Religious Studies'
    ],
    'Oxbridge Interview': [
        'Interview Preparation (General)',
        'Interview Technique',
        'Problem Solving & Critical Thinking',
        'Subject-Specific Interview Prep'
    ]
};

export const MENTOR_ONBOARDING_QUESTIONS: OnboardingQuestion[] = [
    {
        id: 'bio',
        label: 'A brief bio about yourself',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us about your experience and why you want to be a mentor...',
    },
    {
        id: 'expertise',
        label: 'Your areas of expertise',
        type: 'multiselect',
        required: true,
        groupedOptions: SUBJECT_OPTIONS,
    },
    {
        id: 'years_experience',
        label: 'Years of mentoring experience',
        type: 'select',
        required: true,
        options: ['0-1', '1-3', '3-5', '5+'],
    },
    {
        id: 'linkedin_url',
        label: 'LinkedIn Profile URL',
        type: 'text',
        required: false,
        placeholder: 'https://www.linkedin.com/in/yourprofile',
    },
    {
        id: 'photo',
        label: 'Profile Photo',
        type: 'file',
        required: true,
    },
    {
        id: 'cv',
        label: 'Your CV / Resume',
        type: 'file',
        required: true,
    },
];
